create database gradesystem;
use gradesystem;
create table student(sid int(10) primary key,sname char(10),gender char(10));
create table course(cid int(10) primary key,cname char(10));
create table mark(mid int(10) primary key,sid int(10),cid int(10),score int(10),constraint stu foreign key(sid) references student(sid),constraint cou foreign key(cid) references course(cid));
insert into student values(1,'Tom','male');
insert into student values(2,'Jack','male');
insert into student values(3,'Rose','female');
insert into course values(1,'math');
insert into course values(2,'physics');
insert into course values(3,'chemistry');
insert into mark values(1,1,1,80);
insert into mark values(2,2,1,85);
insert into mark values(3,3,1,90);
insert into mark values(4,1,2,60);
insert into mark values(5,2,2,90);
insert into mark values(6,3,2,75);
insert into mark values(7,1,3,95);
insert into mark values(8,2,3,75);
insert into mark values(9,3,3,85);
